name: test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    name: PHPUnit ${{ matrix.phpunit-version }} on PHP ${{ matrix.php-version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
        phpunit-version:
          - '11.1'
          - '12.0'
        exclude:
          - php-version: '8.2'
            phpunit-version: '12.0'
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Require PHPUnit ${{ matrix.phpunit-version }}
        run: composer require --dev phpunit/phpunit:^${{ matrix.phpunit-version }} --with-all-dependencies

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run PHPUnit ${{ matrix.phpunit-version }}
        run: vendor/bin/phpunit --configuration=phpunit.xml.dist
